name: python_basics
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.1
  device_info_plus: ^9.1.1
  dio: ^5.4.3+1
  external_path: ^1.0.3
  flutter_riverpod: ^2.5.1
  gal: ^2.3.0
  intl: ^0.19.0
  path_provider: ^2.1.3
  pdf: ^3.10.8
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3
  uuid: ^4.4.0

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: Sarif
      fonts:
        - asset: assets/fonts/sarif.ttf

    - family: SourceSarif
      fonts:
        - asset: assets/fonts/source-sarif.ttf
